foldd2/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'users#dashboard'

  get "/records/new", :controller => "records", :action => "new"
  post "/create_record", :controller => "records", :action => "create"

  get "/records", :controller => "records", :action => "index"
  get "/records/:id", :controller => "records", :action => "show"

  get "/records/:id/edit", :controller => "records", :action => "edit"
  post "/update_record/:id", :controller => "records", :action => "update"

  get "/delete_record/:id", :controller => "records", :action => "destroy"

  get "/users/new", :controller => "users", :action => "new"
  post "/create_user", :controller => "users", :action => "create"

  get "/users/dashboard", :controller => "users", :action => "dashboard"
  get "/users", :controller => "users", :action => "index"
  get "/users/:id", :controller => "users", :action => "show"

  get "/users/edit", :controller => "users", :action => "edit"
  post "/update_user/:id", :controller => "users", :action => "update"

  get "/delete_user/:id", :controller => "users", :action => "destroy"

end

foldd2/app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
end

foldd2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :records
end

foldd2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :first
  devise_parameter_sanitizer.for(:sign_up) << :last
  devise_parameter_sanitizer.for(:sign_up) << :email
  devise_parameter_sanitizer.for(:sign_up) << :phone
  devise_parameter_sanitizer.for(:sign_up) << :dorm
  devise_parameter_sanitizer.for(:sign_up) << :address1
  devise_parameter_sanitizer.for(:sign_up) << :address2
  devise_parameter_sanitizer.for(:sign_up) << :zip
  devise_parameter_sanitizer.for(:sign_up) << :pud
  devise_parameter_sanitizer.for(:sign_up) << :put
  devise_parameter_sanitizer.for(:sign_up) << :dod
  devise_parameter_sanitizer.for(:sign_up) << :dot

  devise_parameter_sanitizer.for(:account_update) << :first
  devise_parameter_sanitizer.for(:account_update) << :last
  devise_parameter_sanitizer.for(:account_update) << :email
  devise_parameter_sanitizer.for(:account_update) << :phone
  devise_parameter_sanitizer.for(:account_update) << :dorm
  devise_parameter_sanitizer.for(:account_update) << :address1
  devise_parameter_sanitizer.for(:account_update) << :address2
  devise_parameter_sanitizer.for(:account_update) << :zip
  devise_parameter_sanitizer.for(:account_update) << :pud
  devise_parameter_sanitizer.for(:account_update) << :put
  devise_parameter_sanitizer.for(:account_update) << :dod
  devise_parameter_sanitizer.for(:account_update) << :dot
end

end

foldd2/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new
    @record.user_id = params[:user_id]
    @record.pud = Chronic.parse(params[:pud])
    @record.put = Chronic.parse(params[:put])
    @record.dod = Chronic.parse(params[:dod])
    @record.dot = Chronic.parse(params[:dot])

    if @record.save
      redirect_to "/records", :notice => "Record created successfully."
    else
      render 'new'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])

    @record.user_id = params[:user_id]
    @record.pud = Chronic.parse(params[:pud])
    @record.put = Chronic.parse(params[:put])
    @record.dod = Chronic.parse(params[:dod])
    @record.dot = Chronic.parse(params[:dot])

    if @record.save
      redirect_to "/records", :notice => "Record updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @record = Record.find(params[:id])

    @record.destroy

    redirect_to "/records", :notice => "Record deleted."
  end
end

foldd2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard

  end

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first = params[:first]
    @user.last = params[:last]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.dorm = params[:dorm]
    @user.address1 = params[:address1]
    @user.address2 = params[:address2]
    @user.zip = params[:zip]
    @user.pud = params[:pud]
    @user.put = params[:put]
    @user.dod = params[:dod]
    @user.dot = params[:dot]

    if @user.save
      redirect_to "/users", :notice => "User created successfully."
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.first = params[:first]
    @user.last = params[:last]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.dorm = params[:dorm]
    @user.address1 = params[:address1]
    @user.address2 = params[:address2]
    @user.zip = params[:zip]
    @user.pud = params[:pud]
    @user.put = params[:put]
    @user.dod = params[:dod]
    @user.dot = params[:dot]

    if @user.save
      redirect_to "/users", :notice => "User updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy

    redirect_to "/users", :notice => "User deleted."
  end
end

foldd2/app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

foldd2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Foldd2</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cosmo/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="/public/custom.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">Foldd</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
       <!--    <li><a href="/records">Records</a></li>
          <li><a href="/users">Users</a></li> -->
          <!-- <li><a href="#">About</a></li> -->
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><a href="/users/edit">Edit Profile</a></li>
            <li><a href="/users/sign_out" data-method="delete" rel="nofollow">Sign out</a></li>
          <% else %>
            <li><a href="/users/sign_up">Sign up</a></li>
            <li><a href="/users/sign_in">Sign in</a></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

foldd2/app/views/records/edit.html.erb
<!-- Validation failure messages -->

<% if @record.errors.any? %>
  <% @record.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Record #<%= @record.id %></h3>
      </div>
      <div class="panel-body">
        <form action="/update_record/<%= @record.id %>" method="post" class="form-horizontal">
          <!-- Hidden input for authenticity token to protect from forgery -->
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

          <!-- Label and input for user_id -->
         <div class="form-group">
            <label for="user_id" class="col-sm-2 control-label">
              User ID
            </label>
            <div class="col-sm-10">
              <input type="text" id="user_id" name="user_id" placeholder="User" class="form-control" value="<%= @record.user_id %>">
            </div>
          </div>



          <!-- Label and input for pud -->
          <div class="form-group" >
            <label for="pud" class="col-sm-2 control-label">
              Pick Up Date
            </label>
            <div class="col-sm-9 input-group date" id='datetimepicker5'>
              <input type="text" id="pud" name="pud" placeholder="Pud" class="form-control" value="<%= @record.pud %>" >
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
          </div>

          <!-- Label and input for put -->
          <div class="form-group">
            <label for="put" class="col-sm-2 control-label">
              Pick Up Time
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker7'>
              <input type="text" id="put" name="put" placeholder="Put" class="form-control" value="<%= @record.put %>">
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
          </div>

          <!-- Label and input for dod -->
          <div class="form-group">
            <label for="dod" class="col-sm-2 control-label">
              Drop Off Date
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker6'>
              <input type="text" id="dod" name="dod" placeholder="Dod" class="form-control" value="<%= @record.dod %>">
                    <span class="input-group-addon">
                   <span class="glyphicon glyphicon-calendar"></span>
                  </span>
            </div>
          </div>

          <!-- Label and input for dot -->
          <div class="form-group">
            <label for="dot" class="col-sm-2 control-label">
              Drop Off Time
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker8'>
              <input type="text" id="dot" name="dot" placeholder="Dot" class="form-control" value="<%= @record.dot %>">
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button class="btn btn-warning">
                Update Record
              </button>
              or
              <a href="/records/<%= @record.id %>">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

<script type="text/javascript">
  $(function () {
    $('#datetimepicker5').datetimepicker({
      format: 'YYYY-MM-DD'
    });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
    $('#datetimepicker6').datetimepicker({
format: 'YYYY-MM-DD'
    });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
     $('#datetimepicker7').datetimepicker({
                    format: 'LT'
                });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
     $('#datetimepicker8').datetimepicker({
                    format: 'LT'
                });
  });
</script>
<!-- End responsive panel example -->

foldd2/app/views/records/index.html.erb
<div class="page-header">
  <h1>
    Records
    <a href="/records/new" class="btn btn-lg btn-success"><i class="fa fa-plus"></i></a>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Records (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @records.each do |record| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Record #<%= record.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>User ID</dt>
          <dd><%= record.user_id %></dd>

          <dt>Pick Up Date</dt>
          <dd><%= record.try(:pud).try(:strftime, '%A,   %b %d, %Y') %></dd>

          <dt>Pick Up Time</dt>
          <dd><%= record.try(:put).try(:strftime, '%l:%M %P') %></dd>

          <dt>Drop Off Date</dt>
          <dd><%= record.try(:dod).try(:strftime, '%A,   %b %d, %Y') %></dd>

          <dt>Drop Off Time</dt>
          <dd><%= record.try(:dot).try(:strftime, '%l:%M %P') %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <a href="/records/<%= record.id %>" class="btn btn-primary">
            <i class="fa fa-search-plus"></i>
          </a>

          <a href="/records/<%= record.id %>/edit" class="btn btn-warning">
            <i class="fa fa-edit"></i>
          </a>

          <a href="/delete_record/<%= record.id %>" class="btn btn-danger" rel="nofollow">
            <i class="fa fa-trash-o"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- You can ignore the following. It's a quick and dirty example of how to get a Pinterest-style layout with quick search. -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

foldd2/app/views/records/new.html.erb
<!-- Validation failure messages -->

<% if @record.errors.any? %>
  <% @record.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Record</h3>
      </div>
      <div class="panel-body">
        <form action="/create_record" method="post" class="form-horizontal">
          <!-- Hidden input for authenticity token to protect from forgery -->
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

          <!-- Label and input for user_id -->
          <div class="form-group">
            <label for="user_id" class="col-sm-2 control-label">
              User ID
            </label>
            <div class="col-sm-10">
              <input type="text" id="user_id" name="user_id" placeholder="User" class="form-control" value="<%= @record.user_id %>">
            </div>
          </div>



          <!-- Label and input for pud -->
          <div class="form-group" >
            <label for="pud" class="col-sm-2 control-label">
              Pick Up Date
            </label>
            <div class="col-sm-9 input-group date" id='datetimepicker1'>
              <input type="text" id="pud" name="pud" placeholder="Pud" class="form-control" >
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
          </div>

          <!-- Label and input for put -->
          <div class="form-group">
            <label for="put" class="col-sm-2 control-label">
              Pick Up Time
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker3'>
              <input type="text" id="put" name="put" placeholder="Put" class="form-control" value="<%= @record.put %>">
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
          </div>

          <!-- Label and input for dod -->
          <div class="form-group">
            <label for="dod" class="col-sm-2 control-label">
              Drop Off Date
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker2'>
              <input type="text" id="dod" name="dod" placeholder="Dod" class="form-control" value="<%= @record.dod %>">
                    <span class="input-group-addon">
                   <span class="glyphicon glyphicon-calendar"></span>
                  </span>
            </div>
          </div>

          <!-- Label and input for dot -->
          <div class="form-group">
            <label for="dot" class="col-sm-2 control-label">
              Drop Off Time
            </label>
            <div class="col-sm-10 input-group date" id='datetimepicker4'>
              <input type="text" id="dot" name="dot" placeholder="Dot" class="form-control" value="<%= @record.dot %>">
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button class="btn btn-success">
                Create Record
              </button>
              or
              <a href="/records">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker({
      format: 'YYYY-MM-DD'
    });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
    $('#datetimepicker2').datetimepicker({
format: 'YYYY-MM-DD'
    });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
     $('#datetimepicker3').datetimepicker({
                    format: 'LT'
                });
  });
</script>
<!-- End responsive panel example -->
<script type="text/javascript">
  $(function () {
     $('#datetimepicker4').datetimepicker({
                    format: 'LT'
                });
  });
</script>
<!-- End responsive panel example -->

foldd2/app/views/users/dashboard.html.erb
<h1>My Dashboard</h1>

<h2>Welcome, <%= current_user.first %></h2>

<p>Your laundry pick up and delivery address currently is: <%= current_user.dorm %> <%= current_user.address1 %> <%= current_user.address2 %> </p>

<p>Your laundry pick up day is <%= current_user.pud %> and your pick up time is <%= current_user.put %> </p>
<p>Your laundry drop off day is <%= current_user.dod %> and your drop off time is <%= current_user.dot %> </p>


<a href="/users/edit">Click here to edit your profile information.</a>



<h3>Here is a list of your previous transactions</h3>

<% current_user.records.each do |record| %>
<dl>
  <dt>Pick Up Date and Time</dt>
  <dd><%= record.try(:pud).try(:strftime, '%A,   %b %d, %Y') %> at <%= record.try(:put).try(:strftime, '%l:%M %P') %></dd>
  <dt>Drop Off Date and Time</dt>
  <dd><%= record.try(:dod).try(:strftime, '%A,   %b %d, %Y') %> at <%= record.try(:dot).try(:strftime, '%l:%M %P') %></dd>
  </dl>
<% end %>

foldd2/app/views/users/new.html.erb
<!-- Validation failure messages -->

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="jumbotron">
  <h1>Don't hassle with doing your own laundry</h1>
  <p>With Foldd, your laundry will be picked up, washed, folded, and delivered once a week.</p>
<!--   <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p> -->
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://i.imgur.com/OJiNA5P.png" alt="...">
      <div class="caption">
        <h3>1. Pick Up</h3>
        <p>Your clothes will be picked up from your residence each week on the date and time you choose.</p>
        <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://i.imgur.com/Lru0gpr.png" alt="...">
      <div class="caption">
        <h3>2. Wash and Fold</h3>
        <p>We'll wash and fold your laundry at our nearby laundry facility.</p>
        <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://i.imgur.com/ksP7Y09.png" alt="...">
      <div class="caption">
        <h3>3. Clean Clothes Delivered</h3>
        <p>We'll deliver your clean, folded clothes the next day at a time that you request.</p>
        <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>
</div>


<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field form-group">
    <%= f.label :first, 'First Name' %>
    <%= f.text_field :first, autofocus: true, :class => "form-control" %>
  </div>

    <div class="field form-group">
    <%= f.label :last, 'Last Name' %>
    <%= f.text_field :last, autofocus: true, :class => "form-control" %>
  </div>


  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "off", :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :phone, 'Phone Number' %>
    <%= f.telephone_field :phone, autofocus: true, :class => "form-control", :limit => 10 %>
  </div>

  <div class="field form-group">
    <%= f.label :dorm, 'Dorm Name' %>
    <%= f.text_field :dorm, autofocus: true, :class => "form-control" %>
  </div>

    <div class="field form-group">
    <%= f.label :address1, 'Address 1' %>
    <%= f.text_field :address1, autofocus: true, :class => "form-control" %>
  </div>

    <div class="field form-group">
    <%= f.label :address2, 'Address 2' %>
    <%= f.text_field :address2, autofocus: true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :zip, 'Zip Code' %>
    <%= f.number_field :zip, autofocus: true, :class => "form-control" %>
  </div>

  <div class="form-group">
            <label for="pud" class="col-sm-2 control-label">
              Pick Up Date
            </label>
            <div class="col-sm-10">
              <select class="form-control" type="text" id="pud" name="pud" value="<%= @user.pud %>">
  <option>Sunday</option>
  <option>Monday</option>
  <option>Tuesday</option>
</select>
            </div>
          </div>

          <!-- Label and input for put -->
          <div class="form-group">
            <label for="put" class="col-sm-2 control-label">
              Pick Up Time
            </label>
            <div class="col-sm-10">
              <select class="form-control" type="text" id="put" name="put" value="<%= @user.put %>">
  <option>10:00 AM</option>
  <option>11:00 AM</option>
  <option>12:00 PM</option>
  <option>1:00 PM</option>
 <option>2:00 PM</option>
  <option>3:00 PM</option>
  <option>4:00 PM</option>
</select>
            </div>
          </div>

          <!-- Label and input for dod -->
          <div class="form-group">
            <label for="dod" class="col-sm-2 control-label">
              Drop Off Date
            </label>
            <div class="col-sm-10">
              <select class="form-control" type="text" id="dod" name="dod" value="<%= @user.dod %>">
  <option>Monday</option>
  <option>Tuesday</option>
  <option>Wednesday</option>
</select>


            </div>
          </div>

          <!-- Label and input for dot -->
          <div class="form-group">
            <label for="dot" class="col-sm-2 control-label">
              Drop Off Time
            </label>
            <div class="col-sm-10">
              <select class="form-control" type="text" id="dot" name="dot" value="<%= @user.dot %>">
<option>10:00 AM</option>
  <option>11:00 AM</option>
  <option>12:00 PM</option>
  <option>1:00 PM</option>
 <option>2:00 PM</option>
  <option>3:00 PM</option>
  <option>4:00 PM</option>
</select>
            </div>
          </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>